#!/bin/sh

test -n "$*" && scrsaver="$*" || \
scrsaver='htop -s PERCENT_NORM_CPU -M --readonly'

# try exiting GNOME overview
dbus-send --session --dest=org.gnome.Shell --type=method_call --print-reply /org/gnome/Shell org.freedesktop.DBus.Properties.Set string:org.gnome.Shell string:OverviewActive variant:boolean:false

exec cool-retro-term -T '__XSCRSAVER_FEELDEAD__' --fullscreen -e sh -c " \
  stty -echo; \
  while not wmctrl -r __XSCRSAVER_FEELDEAD__ -b add,above; do \
    sleep 0.1; \
  done; \
  clear; \
  unclutter --start-hidden & xscrsaver-wrapper ${scrsaver}; \
  exit 0; \
"
